import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import NavigationBar from "./__navigation_bar/NavigationBar";
import "./globals.css";

const notoSans = Noto_Sans({
  variable: "--font-noto-sans",
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${notoSans.variable} antialiased`}>
        <NavigationBar />
        <main className="wrapper">
          <div>{children}</div>
        </main>
      </body>
    </html>
  );
}
